version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ci

  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: deps
    groups:
      sherpa-onnx:  # sherpa-onnx and sherpa-onnx-core must stay on the same version
        patterns: ["sherpa-onnx*"]
